### ISSUE TITLE
Multinomial law implementation

### ISSUE THREAD

**Issue by arnauddhaene** [EPFL-SV-cpp-projects/Team_7#2]
Coding of a function taking in the necessary parameters in order to return the value of the multinomial law.

**Comment by arnauddhaene** [comment]
@jonathanhaab Ouais je veux bien voir, tu peux l'implémenter dans les classes existantes ou bien créer un fichier (e.g. /divers) et y ajouter le code si jamais tu ne sais pas trop où/comment l'implémenter. (Ou tout simplement le lier sur cette discussion)

**Comment by jonathanhaab** [comment]
Au vu des dernières info du cours du 13.11.17, on a pas besoin d'implémenter de méthode multinomiale à proprement parler. On va simplement utiliser binomial_distribution qui est fourni par la librairie c++

**Comment by arnauddhaene** [comment]
Juste pour vous avertir que les test ne run pas (met un temps infini et fini par crasher). De plus, je me suis permis de changer les occurrences en size_t.
